
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import java.net.InetSocketAddress;

import com.sun.net.httpserver.HttpServer;

import project.handlers.ServerCheckHandler;
import project.handlers.SumHandler;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException{
        System.out.println("Hello world");
        
        // 아래에 문제 해결을 위한 코드를 작성해주세요.
        HttpServer httpServer = HttpServer.create(new InetSocketAddress("0.0.0.0", 5678), 0);
        httpServer.createContext("/", new ServerCheckHandler());
        httpServer.createContext("/sum", new SumHandler());
        httpServer.setExecutor(null);
        httpServer.start();
    }
}
